### ISSUE TITLE
where is it?

### ISSUE THREAD

**Issue by DLP61** [davidlang42/taskban#2]
I went through all the steps - limited as they are - to get this app. NOTHING. NADA. ZIPPO. where is it?

I read that you have an open issue of it disappearing on someone who had it. This could be related. Maybe not. I know nothing about coding I just wanted to use your app. 

And to add a bit more frustration to the process, just to leave you this message, I had to signup on the platform. On the one hand I get it. On the other, I'm not a coder. The only reason I am here is to figure out how to get your app to appear.

**Comment by GuizmoPhil** [comment]
Hey @DLP61 ,

I know you've closed the issue, but in case anyone ends up on this like me after a Google search, here's how I fixed this on my end.

I went into Gmail's settings, opened the plugin manager and installed TaskBan from there. It asked me again to grant permission to my account, so I did, and then the app was installed.

I had to refresh my Gmail's webpage in order to see the new icon of TaskBan in the right sidebar.

I'm still unable to use the app from the URL link on the website, it might be linked to the [issue I've just opened](https://github.com/davidlang42/taskban/issues/3) afterwards. 

For the time being, at least I can enjoy this app wby using the sidebar. When you click on the Tasks list title, it opens a pop-up with the kanban.
