### ISSUE TITLE
URL link to launch the App from your website isn't working.

### ISSUE THREAD

**Issue by GuizmoPhil** [davidlang42/taskban#3]
Hello David,

It seems that the Launch App link on your website does not work. The link point to `https://taskban.davidlang.net/index.html`, which when we click on it, opens a new tab to _https://script.google.com/........etc..._.

That tab only shows a blank page with the following error at the top left of it: `This app is not managed by Google, but by another user.` (This is translated on the fly by my brain from French to English. It might not be the exact message word for word in English, but my Google account is configured in French.)

I've went into my Google App Scripts app to see if there's anything shown. It looks like it detects me accessing the URL, like I would from the pop-up being opened from the Gmail's sidebar. However, the Gmail's sidebar pop-up works.

I'm attaching below two screenshots to help you understand more what I'm saying. 🥯 

![AppsScript execute](https://user-images.githubusercontent.com/10763086/136311311-0c147f9b-731b-47e9-9861-b989334cf2ae.jpg)

![urlissue](https://user-images.githubusercontent.com/10763086/136311312-bcf7cffd-2ab2-4117-aa25-ed64f6cf9fd5.PNG)

**Comment by davidlang42** [comment]
Unfortunately this is due to how I was doing the redirect to make the url look nicer. I've tried a lot of things and it seems for security reasons Google Apps Scripts won't let me redirect the user to my own url, but as a workaround I've added a big ugly redirect button:
![image](https://user-images.githubusercontent.com/37281992/147805047-1f3666bd-2378-4279-97c7-c95e8690871b.png)

At least this way, you can click it yourself and it takes you into TaskBan, rather than not working at all.

Once you've done this, you'll see the url is either `https://taskban.davidlang.net/frame.html` (if you are on the summary page) or `https://taskban.davidlang.net/frame.html?b=Board-Name` (if you are on a board).

Going directly to these links (once you are logged into your Google account and have used TaskBan at least once) will work without a redirect button.
