### ISSUE TITLE
Calendar access and adding from meetings

### ISSUE THREAD

**Issue by josersleal** [davidlang42/taskban#4]
great add-on thank you very much.
A suggestion if possible and you have time.:
- on google calendar, it would be great if one could see the board.
- also dragging an existing meeting from calendar into the board (this one is harder maybe) copying it to a task.

**Comment by davidlang42** [comment]
Hi @josersleal,

Thanks for the feedback, glad you like it! As to your suggestions, unfortunately Google keeps what you can do in the side add-on very limited. There is no way for me to use drag and drop from your calendar, and its not possible to show anything as complicated as the whole TaskBan board.

However I do have a suggestion for using viewing the board. If you click the board link in the addon, it will open the board in a pop-up window, which you can place next to your google calendar window. If you're using Windows (rather than MacOS or Linux) you can simply drag the popup window to the right edge of your screen and it will automatically take up the right half of your screen, leaving the left half as your original Google Calendar window.

Hope this helps!
