### ISSUE TITLE
About future features

### ISSUE THREAD

**Issue by reply2future** [davidlang42/taskban#6]
I would like to contribute the repo but I don't know which tasks have been done and what is the progress.

BTW I am backend dev so  I would learn some knowlege about PWA and Google Apps Script :)

**Comment by davidlang42** [comment]
I'm happy for you to work on any of the features listed in README.MD, I'm not currently working on any of them. Or even other features/improvements you think might be useful. Just make sure they are general features which others might find useful rather than obscure or specific things that only make sense for your own workflow.
