### ISSUE TITLE
Error when deleting a task with a name containing '(' or ')' 

### ISSUE THREAD

**Issue by CJPrindle** [davidlang42/taskban#7]
I believe the task in question was imported. When I tried to delete it I got the following error:

**Task title cannot include '(' or ')'.**

Apparently, a Task title can contain parentheses. You just can't delete it.
![Screenshot from 2022-05-04 01 06 43](https://user-images.githubusercontent.com/14342344/166625883-02a68ae5-a1ce-4266-812c-78ec3870846a.png)

**Comment by davidlang42** [comment]
Hi Christopher,

Thanks for reporting this to me, yes I guess it would be nice if you could just delete a task even if it has an invalid name.
I'll fix this so that doesn't allow you to type '(' or ')' into the name box at all, and it removes them if they are already present.

Just letting you know there is an easy work around for this, just change the title in the "Title" box to not have the '(' and ')' in it, then press delete. Or you can always delete the task through any of the normal ways to access your Google Tasks (eg. in Google Calendar or in the Google Tasks mobile app).

David.

**Comment by davidlang42** [comment]
https://github.com/davidlang42/taskban/commit/24767c55dd5e27285cb8bf8c6fb0e1b4230e4387
